<img src="https://d24cdstip7q8pz.cloudfront.net/t/ineuron1/content/common/images/final%20logo.png" height=50 alt-text="iNeuron.ai logo">

## 18.3 Plotly

Plotly is a free and open-source graphing library for Python.

- The popular Pandas data analysis and manipulation tool provides plotting functions on its `DataFrame` and `Series` objects, which have historically produced matplotlib plots. 

- Since version 0.25, Pandas has provided a mechanism to use different backends, and as of version 4.8 of plotly, you can now use a Plotly Express-powered backend for Pandas plotting. This means you can now produce interactive plots directly from a data frame, without even needing to import Plotly.

### 18.3.1 Installation

- To activate this backend, you will need to have `Plotly` installed.

plotly may be installed using pip
```cmd
pip install plotly
```
or conda.

```cmd
conda install -c plotly plotly
```

- This package contains everything you need to write figures to standalone HTML files.

>**Note:** No internet connection, account, or payment is required to use plotly.py. Prior to version 4, this library could operate in either an "online" or "offline" mode. The documentation tended to emphasize the online mode, where graphs get published to the Chart Studio web service. In version 4, all "online" functionality was removed from the plotly package and is now available as the separate, optional, chart-studio package (See below). plotly.py version 4 is "offline" only, and does not include any functionality for uploading figures or data to cloud services.

- Then just need to set `pd.options.plotting.backend` to `"plotly"` and call `.plot()` to get a `plotly.graph_objects.Figure` object back, just like if you had called Plotly Express directly:

In [4]:
import plotly.graph_objects as go

## It generate a bar graph
fig = go.Figure(data=go.Bar(y=[2, 3, 1]))
fig.write_html('first_figure.html', auto_open=True)
##Double click on first_figure.html file to open in web browser

** Note: Make sure you only have one installation of Python on your computer when you do this, otherwise the installation may not work. **

### 18.3.2 Jupyter Notebook Installation (Additional)
**Note:** If you already have anaconda installed or juputer notebook installed no need to install it again, but check with the specified version also.

For use in the classic Jupyter Notebook, install the notebook and ipywidgets packages using `pip`.

```cmd
pip install "notebook>=5.3" "ipywidgets>=7.2"
```

or conda.
```cmd
conda install "notebook>=5.3" "ipywidgets>=7.2"
```

These packages contain everything you need to run a Jupyter notebook.

```jupyter notebook```

and display plotly figures inline using the notebook renderer.

In [5]:
import plotly.graph_objects as go
fig = go.Figure(data=go.Bar(y=[2, 3, 1]))
fig.show()

### 18.3.3 JupyterLab Installation (Python 3.5+)
For use in JupyterLab, install the jupyterlab and ipywidgets packages using `pip`.

```cmd
pip install jupyterlab "ipywidgets>=7.5"
```

or conda.

```cmd
conda install jupyterlab "ipywidgets=7.5"
```

Then run the following commands to install the required JupyterLab extensions (note that this will require node to be installed):

**JupyterLab renderer support**

```cmd
jupyter labextension install jupyterlab-plotly@4.9.0
```

**OPTIONAL: Jupyter widgets extension**

```cmd
jupyter labextension install @jupyter-widgets/jupyterlab-manager plotlywidget@4.9.0
```

These packages contain everything you need to run JupyterLab

```cmd
jupyter lab
```

and display plotly figures inline using the `plotly_mimetype` renderer.

In [6]:
import plotly.graph_objects as go
fig = go.Figure(data=go.Bar(y=[2, 3, 1]))
fig.show()

### 18.3.4 Plotly Express in Python
Plotly Express is a terse, consistent, high-level API for creating figures.

- The plotly.express module (usually imported as px) contains functions that can create entire figures at once, and is referred to as Plotly Express or PX. 
- Plotly Express is a built-in part of the plotly library, and is the recommended starting point for creating most common figures. 
- Every Plotly Express function uses graph objects internally and returns a plotly.graph_objects.Figure instance. 

- Plotly Express provides more than 30 functions for creating different types of figures. The API for these functions was carefully designed to be as consistent and easy to learn as possible, making it easy to switch from a scatter plot to a bar chart to a histogram to a sunburst chart throughout a data exploration session. Scroll down for a gallery of Plotly Express plots, each made in a single function call.

**Plotly Express currently includes the following functions:**

```
1) Basics: scatter, line, area, bar, funnel, timeline
2) Part-of-Whole: pie, sunburst, treemap, funnel_area
3) 1D Distributions: histogram, box, violin, strip
4) 2D Distributions: density_heatmap, density_contour
5) Matrix Input: imshow
6) 3-Dimensional: scatter_3d, line_3d
7) Multidimensional: scatter_matrix, parallel_coordinates, parallel_categories
8) Tile Maps: scatter_mapbox, line_mapbox, choropleth_mapbox, density_mapbox
9) Outline Maps: scatter_geo, line_geo, choropleth
10) Polar Charts: scatter_polar, line_polar, bar_polar
11) Ternary Charts: scatter_ternary, line_ternary
```

**The following set of figures is just a sampling of what can be done with Plotly Express.**

#### 18.3.4.1 Scatter, Line, Area and Bar Charts

In [7]:
## Scatter Plot
import plotly.express as px

df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
fig.show()

In [8]:
## Scatter Plot with error bar
import plotly.express as px

df = px.data.iris()
df["e"] = df["sepal_width"]/100
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species", error_x="e", error_y="e")
fig.show()

In [10]:
## Scatter Plot with trendlines
import plotly.express as px

df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species", marginal_y="violin",
           marginal_x="box", trendline="ols")
fig.show()

In [11]:
## Bar Chats
import plotly.express as px

df = px.data.tips()
fig = px.bar(df, x="sex", y="total_bill", color="smoker", barmode="group")
fig.show()

In [12]:
## facet plots.
import plotly.express as px

df = px.data.tips()
fig = px.bar(df, x="sex", y="total_bill", color="smoker", barmode="group", facet_row="time", facet_col="day",
       category_orders={"day": ["Thur", "Fri", "Sat", "Sun"], "time": ["Lunch", "Dinner"]})
fig.show()

In [13]:
## scatterplot matrices (SPLOMs).
import plotly.express as px

df = px.data.iris()
fig = px.scatter_matrix(df, dimensions=["sepal_width", "sepal_length", "petal_width", "petal_length"], color="species")
fig.show()

In [14]:
df = px.data.iris()
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [15]:
## Multidimensional Parallel Coordinates
import plotly.express as px

df = px.data.iris()
fig = px.parallel_coordinates(df, color="species_id", labels={"species_id": "Species",
                  "sepal_width": "Sepal Width", "sepal_length": "Sepal Length",
                  "petal_width": "Petal Width", "petal_length": "Petal Length", },
                    color_continuous_scale=px.colors.diverging.Tealrose, color_continuous_midpoint=2)
fig.show()

**More Details of [parallel coordinates](https://plotly.com/python/parallel-coordinates-plot/) and [parallel categories](https://plotly.com/python/parallel-categories-diagram/)**

In [16]:
## Multidimensional Parallel Categories
import plotly.express as px

df = px.data.tips()
fig = px.parallel_categories(df, color="size", color_continuous_scale=px.colors.sequential.Inferno)
fig.show()

In [17]:
## Boubble plots with hover labels.
import plotly.express as px

df = px.data.gapminder()
fig = px.scatter(df.query("year==2007"), x="gdpPercap", y="lifeExp", size="pop", color="continent",
           hover_name="country", log_x=True, size_max=60)
fig.show()

In [18]:
px.data.gapminder()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [19]:
## Animations.
import plotly.express as px

df = px.data.gapminder()
fig = px.scatter(df, x="gdpPercap", y="lifeExp", animation_frame="year", animation_group="country",
           size="iso_num", color="continent", hover_name="country", facet_col="continent",
           log_x=True, size_max=45, range_x=[100,100000], range_y=[25,90])
fig.show()

In [20]:
## Line chart
import plotly.express as px
df = px.data.gapminder()
fig = px.line(df, x="year", y="lifeExp", color="continent", line_group="country", hover_name="country",
        line_shape="spline", render_mode="svg")
fig.show()

In [21]:
## Area Charts
import plotly.express as px

df = px.data.gapminder()
fig = px.area(df, x="year", y="pop", color="continent", line_group="country")
fig.show()

#### 18.3.4.2 Whole Charts

In [22]:
## Make sure to use latest version of `pyplot` to avail all the features
import plotly
print(plotly.__version__)

6.7.0

In [23]:
df =px.data.gapminder()
type(df)

pandas.core.frame.DataFrame

In [24]:
px.data.gapminder().query("year == 2007").query("continent == 'Europe'")

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
83,Austria,Europe,2007,79.829,8199783,36126.492700,AUT,40
119,Belgium,Europe,2007,79.441,10392226,33692.605080,BEL,56
155,Bosnia and Herzegovina,Europe,2007,74.852,4552198,7446.298803,BIH,70
191,Bulgaria,Europe,2007,73.005,7322858,10680.792820,BGR,100
383,Croatia,Europe,2007,75.748,4493312,14619.222720,HRV,191
407,Czech Republic,Europe,2007,76.486,10228744,22833.308510,CZE,203
419,Denmark,Europe,2007,78.332,5468120,35278.418740,DNK,208
527,Finland,Europe,2007,79.313,5238460,33207.084400,FIN,246
539,France,Europe,2007,80.657,61083916,30470.016700,FRA,250
575,Germany,Europe,2007,79.406,82400996,32170.374420,DEU,276
599,Greece,Europe,2007,79.483,10706290,27538.411880,GRC,300
683,Hungary,Europe,2007,73.338,9956108,18008.944440,HUN,348
695,Iceland,Europe,2007,81.757,301931,36180.789190,ISL,352
755,Ireland,Europe,2007,78.885,4109086,40675.996350,IRL,372
779,Italy,Europe,2007,80.546,58147733,28569.719700,ITA,380
1019,Montenegro,Europe,2007,74.543,684736,9253.896111,MNE,499
1091,Netherlands,Europe,2007,79.762,16570613,36797.933320,NLD,528
1151,Norway,Europe,2007,80.196,4627926,49357.190170,NOR,578
1235,Poland,Europe,2007,75.563,38518241,15389.924680,POL,616
1247,Portugal,Europe,2007,78.098,10642836,20509.647770,PRT,620
1283,Romania,Europe,2007,72.476,22276056,10808.475610,ROU,642
1343,Serbia,Europe,2007,74.002,10150265,9786.534714,SRB,688
1379,Slovak Republic,Europe,2007,74.663,5447502,18678.314350,SVK,703
1391,Slovenia,Europe,2007,77.926,2009245,25768.257590,SVN,705
1427,Spain,Europe,2007,80.941,40448191,28821.063700,ESP,724
1475,Sweden,Europe,2007,80.884,9031088,33859.748350,SWE,752
1487,Switzerland,Europe,2007,81.701,7554661,37506.419070,CHE,756
1583,Turkey,Europe,2007,71.777,71158647,8458.276384,TUR,792
1607,United Kingdom,Europe,2007,79.425,60776238,33203.261280,GBR,826

In [25]:
## Pie Chart
import plotly.express as px

df = px.data.gapminder().query("year == 2007").query("continent == 'Europe'")
df.loc[df['pop'] < 2.e6, 'country'] = 'Other countries' # Represent only large countries
fig = px.pie(df, values='pop', names='country', title='Population of European continent')
fig.show()

In [26]:
## Sunburst chart
import plotly.express as px

df = px.data.gapminder().query("year == 2007")
fig = px.sunburst(df, path=['continent', 'country'], values='pop',
                  color='lifeExp', hover_data=['iso_alpha'])
fig.show()

In [27]:
## Treemaps
import plotly.express as px

import numpy as np
df = px.data.gapminder().query("year == 2007")
fig = px.treemap(df, path=[px.Constant('sudh'), 'continent', 'country'], values='pop',
                  color='lifeExp', hover_data=['iso_alpha'])
fig.show()

#### 18.3.4.3 1D Distributions

In [28]:
## Histograms.
import plotly.express as px

df = px.data.tips()
fig = px.histogram(df, x="total_bill", y="tip", color="sex", marginal="rug", hover_data=df.columns)
fig.show()

In [29]:
## Box plots.
import plotly.express as px

df = px.data.tips()
fig = px.box(df, x="day", y="tip", color="smoker", notched=True)
fig.show()

In [30]:
px.data.tips()

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [31]:
## Violin plots.
import plotly.express as px

df = px.data.tips()
fig = px.violin(df, y="tip", x="smoker", color="sex", box=True, points="all", hover_data=df.columns)
fig.show()

In [32]:
import plotly.express as px
df = px.data.tips()
fig = px.strip(df, x="total_bill", y="time", orientation="h", color="smoker")
fig.show()

#### 18.3.4.4 2D Distributions

In [33]:
## Density Contour Plot
import plotly.express as px
df = px.data.iris()
fig = px.density_contour(df, x="sepal_width", y="sepal_length")
fig.show()

In [34]:
## Density Contour Plot with distribution
import plotly.express as px

df = px.data.iris()
fig = px.density_contour(df, x="sepal_width", y="sepal_length", color="species", marginal_x="rug", marginal_y="histogram")
fig.show()

In [35]:
## Density Heatmap
import plotly.express as px

df = px.data.iris()
fig = px.density_heatmap(df, x="sepal_width", y="sepal_length", marginal_x="rug", marginal_y="histogram")
fig.show()

#### 18.3.4.5 Images and Heatmaps

In [36]:
## Heatmaps and Images.

import plotly.express as px

fig = px.imshow([[1, 40, 30],
                 [20, 1, 60],
                 [30, 90, 1]])
fig.show()

In [37]:
## RGB Image show
import plotly.express as px

import numpy as np
img_rgb = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
                    [[0, 255, 0], [0, 0, 255], [255, 0, 0]]
                   ], dtype=np.uint8)
fig = px.imshow(img_rgb)
fig.show()

In [38]:
px.data.election()

,district,Coderre,Bergeron,Joly,total,winner,result,district_id
0,101-Bois-de-Liesse,2481,1829,3024,7334,Joly,plurality,101
1,102-Cap-Saint-Jacques,2525,1163,2675,6363,Joly,plurality,102
2,11-Sault-au-Récollet,3348,2770,2532,8650,Coderre,plurality,11
3,111-Mile-End,1734,4782,2514,9030,Bergeron,majority,111
4,112-DeLorimier,1770,5933,3044,10747,Bergeron,majority,112
5,113-Jeanne-Mance,1455,3599,2316,7370,Bergeron,plurality,113
6,12-Saint-Sulpice,3252,2521,2543,8316,Coderre,plurality,12
7,121-La Pointe-aux-Prairies,5456,1760,3330,10546,Coderre,majority,121
8,122-Pointe-aux-Trembles,4734,1879,2852,9465,Coderre,majority,122
9,123-Rivière-des-Prairies,5737,958,1656,8351,Coderre,majority,123
10,13-Ahuntsic,2979,3430,2873,9282,Bergeron,plurality,13
11,131-Saint-Édouard,1827,6408,2815,11050,Bergeron,majority,131
12,132-Étienne-Desmarteau,2331,5748,2788,10867,Bergeron,majority,132
13,133-Vieux-Rosemont,2670,4962,3234,10866,Bergeron,plurality,133
14,134-Marie-Victorin,3673,3155,2431,9259,Coderre,plurality,134
15,14-Bordeaux-Cartierville,3612,1554,2081,7247,Coderre,plurality,14
16,141-Côte-de-Liesse,4308,1320,3959,9587,Coderre,plurality,141
17,142-Norman-McLaren,4104,1459,2822,8385,Coderre,plurality,142
18,151-Saint-Léonard-Est,3931,882,1641,6454,Coderre,majority,151
19,152-Saint-Léonard-Ouest,5387,1184,1908,8479,Coderre,majority,152
20,161-Saint-HenriPetite-BourgognePointe-Saint-Ch...,2432,3368,3578,9378,Joly,plurality,161
21,162-Saint-PaulÉmard,2566,2092,2438,7096,Coderre,plurality,162
22,171-ChamplainL'Île-des-Soeurs,3347,2562,3291,9200,Coderre,plurality,171
23,172-Desmarchais-Crawford,2476,2631,2849,7956,Joly,plurality,172
24,181-Peter-McGill,1451,754,1894,4099,Joly,plurality,181
25,182-Saint-Jacques,1906,2169,2282,6357,Joly,plurality,182
26,183-Sainte-Marie,1347,2827,2271,6445,Bergeron,plurality,183
27,191-Saint-Michel,3668,984,1220,5872,Coderre,majority,191
28,192-François-Perrault,2878,2666,2039,7583,Coderre,plurality,192
29,193-Villeray,2201,5819,2782,10802,Bergeron,majority,193
30,194-Parc-Extension,2420,1793,1402,5615,Coderre,plurality,194
31,21-Ouest,2184,691,1076,3951,Coderre,majority,21
32,22-Est,1589,708,1172,3469,Coderre,plurality,22
33,23-Centre,2526,851,1286,4663,Coderre,majority,23
34,31-Darlington,1873,1182,1232,4287,Coderre,plurality,31
35,32-Côte-des-Neiges,1644,1950,1578,5172,Bergeron,plurality,32
36,33-Snowdon,1548,1503,1636,4687,Joly,plurality,33
37,34-Notre-Dame-de-Grâce,1773,2653,3262,7688,Joly,plurality,34
38,35-Loyola,2040,1437,2648,6125,Joly,plurality,35
39,41-du Canal,1165,832,1266,3263,Joly,plurality,41
40,42-J.-Émery-Provost,1193,653,1157,3003,Coderre,plurality,42
41,43-Fort-Rolland,1325,1205,1908,4438,Joly,plurality,43
42,51-Sault-Saint-Louis,4201,1642,3717,9560,Coderre,plurality,51
43,52-Cecil-P.-Newman,3536,1330,2943,7809,Coderre,plurality,52
44,61-Pierre-Foretier,631,258,998,1887,Joly,majority,61
45,62-Denis-Benjamin-Viger,595,226,1068,1889,Joly,majority,62
46,63-Jacques-Bizard,518,224,690,1432,Joly,plurality,63
47,64-Sainte-Geneviève,332,131,326,789,Coderre,plurality,64
48,71-Tétreaultville,3694,2589,3454,9737,Coderre,plurality,71
49,72-MaisonneuveLongue-Pointe,2746,3250,3139,9135,Bergeron,plurality,72
50,73-Hochelaga,1546,3679,2675,7900,Bergeron,plurality,73
51,74-Louis-Riel,3509,2178,2338,8025,Coderre,plurality,74
52,81-Marie-Clarac,6591,1085,1435,9111,Coderre,majority,81
53,82-Ovide-Clermont,6229,780,1051,8060,Coderre,majority,82
54,91-Claude-Ryan,996,643,423,2062,Coderre,plurality,91
55,92-Joseph-Beaubien,540,833,592,1965,Bergeron,plurality,92
56,93-Robert-Bourassa,446,465,419,1330,Bergeron,plurality,93
57,94-Jeanne-Sauvé,491,698,489,1678,Bergeron,plurality,94

#### 18.3.4.6 3D Coordinates

In [39]:
## 3D scatter plots
import plotly.express as px

df = px.data.election()
fig = px.scatter_3d(df, x="Joly", y="Coderre", z="Bergeron", color="winner", size="total", hover_name="district",
                  symbol="result", color_discrete_map = {"Joly": "blue", "Bergeron": "green", "Coderre":"red"})
fig.show()

#### 18.3.5.7 Tile maps and point on tile maps.

In [40]:
px.data.carshare()

     centroid_lat  centroid_lon    car_hours  peak_hour
0       45.471549    -73.588684  1772.750000          2
1       45.543865    -73.562456   986.333333         23
2       45.487640    -73.642767   354.750000         20
3       45.522870    -73.595677   560.166667         23
4       45.453971    -73.738946  2836.666667         19
..            ...           ...          ...        ...
244     45.547171    -73.556258   951.416667          3
245     45.546482    -73.574939   795.416667          2
246     45.495523    -73.627725   425.750000          8
247     45.521199    -73.581789  1044.833333         17
248     45.532564    -73.567535   694.916667          5

[249 rows x 4 columns]

In [41]:
## Scatter Mapbox
import plotly.express as px

df = px.data.carshare() #Each row represents the availability of car-sharing services near the centroid of a zone in Montreal over a month-long period.
fig = px.scatter_mapbox(df, lat="centroid_lat", lon="centroid_lon", color="peak_hour", size="car_hours",
                  color_continuous_scale=px.colors.cyclical.IceFire, size_max=15, zoom=10,
                  mapbox_style="carto-positron")
fig.show()

C:\Users\nayak\AppData\Local\Temp\ipykernel_6236\462167445.py:5: DeprecationWarning: *scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig = px.scatter_mapbox(df, lat="centroid_lat", lon="centroid_lon", color="peak_hour", size="car_hours",

In [42]:
## Tile map GeoJSON choropleths.
import plotly.express as px

df = px.data.election() #Each feature represents an electoral district in the 2013 Montreal mayoral election.
geojson = px.data.election_geojson()

fig = px.choropleth_mapbox(df, geojson=geojson, color="Bergeron",
                           locations="district", featureidkey="properties.district",
                           center={"lat": 45.5517, "lon": -73.7073},
                           mapbox_style="carto-positron", zoom=9)
fig.show()

C:\Users\nayak\AppData\Local\Temp\ipykernel_6236\2340434254.py:7: DeprecationWarning: *choropleth_mapbox* is deprecated! Use *choropleth_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/
  fig = px.choropleth_mapbox(df, geojson=geojson, color="Bergeron",

In [43]:
px.data.election()

,district,Coderre,Bergeron,Joly,total,winner,result,district_id
0,101-Bois-de-Liesse,2481,1829,3024,7334,Joly,plurality,101
1,102-Cap-Saint-Jacques,2525,1163,2675,6363,Joly,plurality,102
2,11-Sault-au-Récollet,3348,2770,2532,8650,Coderre,plurality,11
3,111-Mile-End,1734,4782,2514,9030,Bergeron,majority,111
4,112-DeLorimier,1770,5933,3044,10747,Bergeron,majority,112
5,113-Jeanne-Mance,1455,3599,2316,7370,Bergeron,plurality,113
6,12-Saint-Sulpice,3252,2521,2543,8316,Coderre,plurality,12
7,121-La Pointe-aux-Prairies,5456,1760,3330,10546,Coderre,majority,121
8,122-Pointe-aux-Trembles,4734,1879,2852,9465,Coderre,majority,122
9,123-Rivière-des-Prairies,5737,958,1656,8351,Coderre,majority,123
10,13-Ahuntsic,2979,3430,2873,9282,Bergeron,plurality,13
11,131-Saint-Édouard,1827,6408,2815,11050,Bergeron,majority,131
12,132-Étienne-Desmarteau,2331,5748,2788,10867,Bergeron,majority,132
13,133-Vieux-Rosemont,2670,4962,3234,10866,Bergeron,plurality,133
14,134-Marie-Victorin,3673,3155,2431,9259,Coderre,plurality,134
15,14-Bordeaux-Cartierville,3612,1554,2081,7247,Coderre,plurality,14
16,141-Côte-de-Liesse,4308,1320,3959,9587,Coderre,plurality,141
17,142-Norman-McLaren,4104,1459,2822,8385,Coderre,plurality,142
18,151-Saint-Léonard-Est,3931,882,1641,6454,Coderre,majority,151
19,152-Saint-Léonard-Ouest,5387,1184,1908,8479,Coderre,majority,152
20,161-Saint-HenriPetite-BourgognePointe-Saint-Ch...,2432,3368,3578,9378,Joly,plurality,161
21,162-Saint-PaulÉmard,2566,2092,2438,7096,Coderre,plurality,162
22,171-ChamplainL'Île-des-Soeurs,3347,2562,3291,9200,Coderre,plurality,171
23,172-Desmarchais-Crawford,2476,2631,2849,7956,Joly,plurality,172
24,181-Peter-McGill,1451,754,1894,4099,Joly,plurality,181
25,182-Saint-Jacques,1906,2169,2282,6357,Joly,plurality,182
26,183-Sainte-Marie,1347,2827,2271,6445,Bergeron,plurality,183
27,191-Saint-Michel,3668,984,1220,5872,Coderre,majority,191
28,192-François-Perrault,2878,2666,2039,7583,Coderre,plurality,192
29,193-Villeray,2201,5819,2782,10802,Bergeron,majority,193
30,194-Parc-Extension,2420,1793,1402,5615,Coderre,plurality,194
31,21-Ouest,2184,691,1076,3951,Coderre,majority,21
32,22-Est,1589,708,1172,3469,Coderre,plurality,22
33,23-Centre,2526,851,1286,4663,Coderre,majority,23
34,31-Darlington,1873,1182,1232,4287,Coderre,plurality,31
35,32-Côte-des-Neiges,1644,1950,1578,5172,Bergeron,plurality,32
36,33-Snowdon,1548,1503,1636,4687,Joly,plurality,33
37,34-Notre-Dame-de-Grâce,1773,2653,3262,7688,Joly,plurality,34
38,35-Loyola,2040,1437,2648,6125,Joly,plurality,35
39,41-du Canal,1165,832,1266,3263,Joly,plurality,41
40,42-J.-Émery-Provost,1193,653,1157,3003,Coderre,plurality,42
41,43-Fort-Rolland,1325,1205,1908,4438,Joly,plurality,43
42,51-Sault-Saint-Louis,4201,1642,3717,9560,Coderre,plurality,51
43,52-Cecil-P.-Newman,3536,1330,2943,7809,Coderre,plurality,52
44,61-Pierre-Foretier,631,258,998,1887,Joly,majority,61
45,62-Denis-Benjamin-Viger,595,226,1068,1889,Joly,majority,62
46,63-Jacques-Bizard,518,224,690,1432,Joly,plurality,63
47,64-Sainte-Geneviève,332,131,326,789,Coderre,plurality,64
48,71-Tétreaultville,3694,2589,3454,9737,Coderre,plurality,71
49,72-MaisonneuveLongue-Pointe,2746,3250,3139,9135,Bergeron,plurality,72
50,73-Hochelaga,1546,3679,2675,7900,Bergeron,plurality,73
51,74-Louis-Riel,3509,2178,2338,8025,Coderre,plurality,74
52,81-Marie-Clarac,6591,1085,1435,9111,Coderre,majority,81
53,82-Ovide-Clermont,6229,780,1051,8060,Coderre,majority,82
54,91-Claude-Ryan,996,643,423,2062,Coderre,plurality,91
55,92-Joseph-Beaubien,540,833,592,1965,Bergeron,plurality,92
56,93-Robert-Bourassa,446,465,419,1330,Bergeron,plurality,93
57,94-Jeanne-Sauvé,491,698,489,1678,Bergeron,plurality,94

In [44]:
px.data.election_geojson()

{'type': 'FeatureCollection',
 'features': [{'type': 'Feature',
   'geometry': {'type': 'MultiPolygon',
    'coordinates': [[[[-73.6363215300962, 45.5759177646435],
       [-73.6362833815582, 45.5758266113331],
       [-73.6446417578686, 45.5658132919643],
       [-73.6453511352974, 45.5647725775888],
       [-73.648867564748, 45.5586898267402],
       [-73.6513170845065, 45.5545659435652],
       [-73.6515658357324, 45.5554439857955],
       [-73.6660837831645, 45.5596724837829],
       [-73.6706609041685, 45.5610978251999],
       [-73.6676019919116, 45.5632340862888],
       [-73.6645385824068, 45.5642716484367],
       [-73.663663123697, 45.5654269638586],
       [-73.663336397858, 45.5666288247853],
       [-73.6637764768649, 45.5678900619231],
       [-73.6625073244826, 45.5688479494114],
       [-73.6624620526633, 45.5708304456346],
       [-73.6620201425015, 45.5713925326191],
       [-73.6616100197742, 45.5737924780218],
       [-73.6612199500215, 45.5747171555678],
       [-73.6625087613399, 45.5748980132699],
       [-73.6639172423219, 45.5730041908097],
       [-73.6654358660443, 45.5729040009532],
       [-73.6661069174428, 45.5737928224235],
       [-73.6657870687343, 45.574385118162],
       [-73.6636711124334, 45.577018676761],
       [-73.6620928771361, 45.578161887933],
       [-73.6611738698168, 45.5798517041392],
       [-73.660404649744, 45.5806752214364],
       [-73.659760079306, 45.5804007503503],
       [-73.6604711314507, 45.5793767269523],
       [-73.660479658497, 45.5787710701802],
       [-73.6613549575147, 45.5780184952852],
       [-73.6617871566128, 45.5758213640561],
       [-73.6607445476436, 45.5764832852254],
       [-73.6608243059909, 45.5774702934068],
       [-73.6592236423267, 45.5793785624903],
       [-73.6570262958283, 45.5810509513563],
       [-73.6552694168748, 45.5819333817794],
       [-73.6543058972308, 45.5836262624158],
       [-73.652557313063, 45.5826892716542],
       [-73.6363215300962, 45.5759177646435]]],
     [[[-73.6561004885273, 45.5841347974261],
       [-73.656376117147, 45.5845383929424],
       [-73.6559939844354, 45.585868003125],
       [-73.6552168328229, 45.5855392416017],
       [-73.6561004885273, 45.5841347974261]]]]},
   'properties': {'district': '11-Sault-au-Récollet'},
   'id': '11'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.6217484540132, 45.5544783077209],
      [-73.6235005117779, 45.5536358848324],
      [-73.6278096771011, 45.5513024018691],
      [-73.6301686544477, 45.5503989164938],
      [-73.6325600663803, 45.5499795021129],
      [-73.6342899238824, 45.5494628161417],
      [-73.6363671046978, 45.548169415833],
      [-73.6398673671325, 45.5441488267699],
      [-73.6407295659042, 45.5429686686779],
      [-73.6485543103777, 45.5308320827376],
      [-73.6510270564502, 45.5263874543882],
      [-73.6555330494037, 45.5277342274232],
      [-73.6698852350516, 45.5318835785726],
      [-73.6726124365382, 45.5322997327559],
      [-73.6747555535799, 45.5323081056009],
      [-73.6764129283619, 45.5321264506516],
      [-73.683124268159, 45.5305991300384],
      [-73.6807721370907, 45.534331320177],
      [-73.6785046215606, 45.5379069417581],
      [-73.6752852955733, 45.5369404343695],
      [-73.6740837310465, 45.5378868187786],
      [-73.6687347480061, 45.5363337408676],
      [-73.667891862525, 45.5387409623539],
      [-73.664945183105, 45.5382590909533],
      [-73.6646235398403, 45.5394847807605],
      [-73.662249203322, 45.543633408253],
      [-73.6616100449503, 45.5441416421638],
      [-73.6604302515405, 45.5460790656787],
      [-73.6568659704249, 45.5450525873044],
      [-73.6513170845065, 45.5545659435652],
      [-73.648867564748, 45.5586898267402],
      [-73.6453511352974, 45.5647725775888],
      [-73.6240413737876, 45.5555253903511],
      [-73.6217484540132, 45.5544783077209]]]},
   'properties': {'district': '12-Saint-Sulpice'},
   'id': '12'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.6513170845065, 45.5545659435652],
      [-73.6568659704249, 45.5450525873044],
      [-73.6604302515405, 45.5460790656787],
      [-73.6616100449503, 45.5441416421638],
      [-73.662249203322, 45.543633408253],
      [-73.6646235398403, 45.5394847807605],
      [-73.664945183105, 45.5382590909533],
      [-73.667891862525, 45.5387409623539],
      [-73.6687347480061, 45.5363337408676],
      [-73.6740837310465, 45.5378868187786],
      [-73.6752852955733, 45.5369404343695],
      [-73.6785046215606, 45.5379069417581],
      [-73.6807721370907, 45.534331320177],
      [-73.6920199187781, 45.5394683031028],
      [-73.702520410412, 45.5431766227664],
      [-73.7042065154565, 45.5438906316964],
      [-73.7043014929187, 45.5441905861876],
      [-73.7027027602765, 45.5451406840713],
      [-73.7023335988111, 45.5457621950639],
      [-73.7012226911876, 45.5459702396396],
      [-73.7004635154173, 45.5466167282154],
      [-73.6996123824321, 45.5464852570484],
      [-73.6992033294858, 45.5475781625301],
      [-73.6968595536907, 45.5481581755357],
      [-73.6949311086011, 45.5474604427764],
      [-73.6924688517172, 45.5472280284581],
      [-73.6891281157722, 45.5477334249253],
      [-73.6879273316976, 45.5481318231022],
      [-73.6865595013798, 45.5491308196528],
      [-73.6852748086046, 45.5488162600605],
      [-73.6827845213391, 45.5489146412483],
      [-73.6801283681886, 45.549462773374],
      [-73.6791182211476, 45.5500801562043],
      [-73.6772981030339, 45.5516675115113],
      [-73.6765545558035, 45.552766523393],
      [-73.6744642269172, 45.5548591969672],
      [-73.6730096784532, 45.5582339830541],
      [-73.6706609041685, 45.5610978251999],
      [-73.6660837831645, 45.5596724837829],
      [-73.6515658357324, 45.5554439857955],
      [-73.6513170845065, 45.5545659435652]]]},
   'properties': {'district': '13-Ahuntsic'},
   'id': '13'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.7043014929187, 45.5441905861876],
      [-73.7042065154565, 45.5438906316964],
      [-73.702520410412, 45.5431766227664],
      [-73.6920199187781, 45.5394683031028],
      [-73.6807721370907, 45.534331320177],
      [-73.683124268159, 45.5305991300384],
      [-73.685195685208, 45.5301022578388],
      [-73.6870922504792, 45.5286619976995],
      [-73.6897803429098, 45.5288476157777],
      [-73.6939612003867, 45.528347826243],
      [-73.6963296087078, 45.5276805484038],
      [-73.7091218538247, 45.5230954877394],
      [-73.7112612170074, 45.5243023856458],
      [-73.7131122096208, 45.5251637887575],
      [-73.7145584630039, 45.5239315629596],
      [-73.7172924358234, 45.5256928911099],
      [-73.7185119695016, 45.5247508136954],
      [-73.7217031155859, 45.5267447688191],
      [-73.7280602953464, 45.5213554616816],
      [-73.7317546325275, 45.5236815365784],
      [-73.7358987648866, 45.5207291683311],
      [-73.7285097856203, 45.5160943522463],
      [-73.7350991221023, 45.5137867482303],
      [-73.7550630650544, 45.5065238038199],
      [-73.7551669017747, 45.5064862077527],
      [-73.7612752776246, 45.5104175090183],
      [-73.7638683329059, 45.5120860463668],
      [-73.762390301954, 45.5126791739444],
      [-73.7600609683013, 45.5141288858482],
      [-73.7568442082942, 45.5171884494623],
      [-73.7548593171474, 45.5180889539846],
      [-73.752606980088, 45.5185523798859],
      [-73.749151955166, 45.519018390863],
      [-73.7452110015187, 45.5215286261207],
      [-73.7437662661847, 45.5231373686573],
      [-73.7411211602605, 45.526837900694],
      [-73.7394306858002, 45.5285277381045],
      [-73.7360589393138, 45.5302671129156],
      [-73.7343347000828, 45.5309824138834],
      [-73.7311072638005, 45.5320095049916],
      [-73.7283844986554, 45.533203827821],
      [-73.7249729419404, 45.5359178137401],
      [-73.7231098233772, 45.5369689627545],
      [-73.7202103870331, 45.5381794076214],
      [-73.7181375140605, 45.5387109207903],
      [-73.7158043157039, 45.5388996570908],
      [-73.7135388429561, 45.5396848689224],
      [-73.7111454931799, 45.541340948266],
      [-73.7091038651233, 45.5430898357363],
      [-73.7078456046825, 45.5423008892929],
      [-73.7069875096913, 45.5436077713277],
      [-73.705614345008, 45.5441267025504],
      [-73.7043014929187, 45.5441905861876]]]},
   'properties': {'district': '14-Bordeaux-Cartierville'},
   'id': '14'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.5576871015794, 45.5932166140624],
      [-73.5694206600629, 45.5971486400825],
      [-73.5696609688417, 45.5965806032278],
      [-73.5726733802096, 45.5977479911912],
      [-73.5745938220503, 45.5986717630315],
      [-73.576232424293, 45.5992577290381],
      [-73.5771288919308, 45.599852413767],
      [-73.5889961999073, 45.6050220349527],
      [-73.5971103983983, 45.6085989887758],
      [-73.6013378366857, 45.6104025414741],
      [-73.6028907661658, 45.6112216102358],
      [-73.601559767966, 45.6118073578371],
      [-73.6023660828945, 45.6125718329314],
      [-73.5984976040034, 45.6140840514745],
      [-73.5954830428467, 45.6158123480652],
      [-73.5740068269183, 45.6304929149516],
      [-73.5683379250343, 45.6341956640577],
      [-73.5514095863784, 45.6269444197056],
      [-73.5481773494253, 45.6255197854529],
      [-73.5585223912755, 45.6137280036474],
      [-73.5640615699407, 45.6074316710882],
      [-73.564986439275, 45.60561620283],
      [-73.5662995431109, 45.6039974029119],
      [-73.5631517029922, 45.6031634368599],
      [-73.5614050931716, 45.6025489377902],
      [-73.5567925816714, 45.6005393547562],
      [-73.5589887922886, 45.5979945383903],
      [-73.5595164040348, 45.5961661000645],
      [-73.5564557704867, 45.5951543577536],
      [-73.5576871015794, 45.5932166140624]]]},
   'properties': {'district': '21-Ouest'},
   'id': '21'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.5452799498143, 45.5959627917351],
      [-73.5491007054645, 45.5975302159963],
      [-73.5479841638628, 45.5989434662401],
      [-73.5468145864499, 45.6013644519429],
      [-73.5461968110206, 45.6046211322422],
      [-73.549913736884, 45.605150517886],
      [-73.5533688744189, 45.605412630486],
      [-73.5524302953106, 45.6080081462088],
      [-73.5507759763854, 45.6103339985918],
      [-73.5585223912755, 45.6137280036474],
      [-73.5481773494253, 45.6255197854529],
      [-73.5358870172169, 45.620207093019],
      [-73.5374747721378, 45.6166252950092],
      [-73.5375256945614, 45.6160673327401],
      [-73.5381703589619, 45.6139517855176],
      [-73.5437218072693, 45.6149096422408],
      [-73.5452777806501, 45.6141657083913],
      [-73.5462767505068, 45.6127238289344],
      [-73.5444977198785, 45.6121760838565],
      [-73.5453373826653, 45.6107633861198],
      [-73.5441363974969, 45.6102716461918],
      [-73.5412098839782, 45.6095033241271],
      [-73.5416434070878, 45.6081797015109],
      [-73.540900931842, 45.6078533012629],
      [-73.5416213388458, 45.606939681157],
      [-73.5375401492111, 45.6052359766051],
      [-73.5365038947396, 45.6026457300995],
      [-73.5365958888719, 45.602162446611],
      [-73.5394321608651, 45.6030910243993],
      [-73.5421763850909, 45.6042454438226],
      [-73.5429289535666, 45.6032316351511],
      [-73.539729971205, 45.6018186221009],
      [-73.5407418924341, 45.6006998521118],
      [-73.5447576674512, 45.6019410417126],
      [-73.5451108447268, 45.6000061818095],
      [-73.5445859643042, 45.5999308464328],
      [-73.5442050076359, 45.5981948225546],
      [-73.5438572127564, 45.5980784963673],
      [-73.5452799498143, 45.5959627917351]]]},
   'properties': {'district': '22-Est'},
   'id': '22'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.5576871015794, 45.5932166140624],
      [-73.5564557704867, 45.5951543577536],
      [-73.5595164040348, 45.5961661000645],
      [-73.5589887922886, 45.5979945383903],
      [-73.5567925816714, 45.6005393547562],
      [-73.5614050931716, 45.6025489377902],
      [-73.5631517029922, 45.6031634368599],
      [-73.5662995431109, 45.6039974029119],
      [-73.564986439275, 45.60561620283],
      [-73.5640615699407, 45.6074316710882],
      [-73.5585223912755, 45.6137280036474],
      [-73.5507759763854, 45.6103339985918],
      [-73.5524302953106, 45.6080081462088],
      [-73.5533688744189, 45.605412630486],
      [-73.549913736884, 45.605150517886],
      [-73.5461968110206, 45.6046211322422],
      [-73.5468145864499, 45.6013644519429],
      [-73.5479841638628, 45.5989434662401],
      [-73.5491007054645, 45.5975302159963],
      [-73.5452799498143, 45.5959627917351],
      [-73.5455045323429, 45.5956272275911],
      [-73.545930102715, 45.5949937733284],
      [-73.5473484500099, 45.5955355370728],
      [-73.5481396292151, 45.5946360429193],
      [-73.5465394629102, 45.5940712033384],
      [-73.5489394765731, 45.5903029802044],
      [-73.5576871015794, 45.5932166140624]]]},
   'properties': {'district': '23-Centre'},
   'id': '23'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.6207592308166, 45.5138993727882],
      [-73.6236560898078, 45.5106541632808],
      [-73.624384898555, 45.5091582170891],
      [-73.6260875230251, 45.507277208983],
      [-73.6279506225702, 45.5061120243158],
      [-73.628749836468, 45.5048079525531],
      [-73.6304494685866, 45.5028490467289],
      [-73.6256440443835, 45.500662130816],
      [-73.6331323407225, 45.49234917306],
      [-73.6480439724158, 45.4990451424615],
      [-73.6458072174417, 45.5016289991394],
      [-73.6422399591459, 45.5054987858353],
      [-73.6423036889254, 45.5062221151428],
      [-73.6415508188144, 45.5069829054595],
      [-73.6416660769228, 45.5076101030023],
      [-73.6385805807369, 45.5112159439382],
      [-73.6365911851412, 45.5146566965285],
      [-73.6357295158589, 45.5143963845137],
      [-73.6346269691423, 45.5156528191911],
      [-73.6289040380069, 45.5140823858644],
      [-73.6267223236567, 45.5165801475772],
      [-73.6207592308166, 45.5138993727882]]]},
   'properties': {'district': '31-Darlington'},
   'id': '31'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.5956108742759, 45.504064067218],
      [-73.5941401789655, 45.5033436344744],
      [-73.594737745289, 45.5028667176493],
      [-73.5977240363362, 45.5016310280474],
      [-73.5997960499359, 45.5001439911523],
      [-73.6009279740317, 45.4988800346583],
      [-73.6033750499038, 45.4967309718248],
      [-73.6044775189475, 45.4952226776326],
      [-73.6068399722065, 45.4952769144878],
      [-73.6083680626652, 45.493592693099],
      [-73.6093606035265, 45.4939788081012],
      [-73.6115925457235, 45.4916920833656],
      [-73.6147351668377, 45.4930299583055],
      [-73.6184160919695, 45.4889467204633],
      [-73.618423454854, 45.4881800607925],
      [-73.6153515138627, 45.4867956883177],
      [-73.6169038962737, 45.4851011880198],
      [-73.6331323407225, 45.49234917306],
      [-73.6256440443835, 45.500662130816],
      [-73.6304494685866, 45.5028490467289],
      [-73.628749836468, 45.5048079525531],
      [-73.6279506225702, 45.5061120243158],
      [-73.6260875230251, 45.507277208983],
      [-73.624384898555, 45.5091582170891],
      [-73.6236560898078, 45.5106541632808],
      [-73.6207592308166, 45.5138993727882],
      [-73.6176645335398, 45.5125000231349],
      [-73.617959519301, 45.5121686212918],
      [-73.61888001694, 45.5111346532789],
      [-73.6169256431203, 45.5102737338336],
      [-73.6178928803835, 45.5091750557282],
      [-73.6160933747766, 45.5082725969653],
      [-73.6189454361275, 45.5051234940594],
      [-73.6182356279483, 45.504722156916],
      [-73.6130513861854, 45.5104478685544],
      [-73.6063535452531, 45.5074911306599],
      [-73.6061344132343, 45.5068772235294],
      [-73.6035337540631, 45.5057001623398],
      [-73.6024762927983, 45.5068574351344],
      [-73.5993805679324, 45.5053898653966],
      [-73.5987846893921, 45.5056180649425],
      [-73.5956108742759, 45.504064067218]]]},
   'properties': {'district': '32-Côte-des-Neiges'},
   'id': '32'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.6458072174417, 45.5016289991394],
      [-73.6480439724158, 45.4990451424615],
      [-73.6331323407225, 45.49234917306],
      [-73.6169038962737, 45.4851011880198],
      [-73.6171481421592, 45.4848346166979],
      [-73.6143642141962, 45.4835868912093],
      [-73.6159143530659, 45.4828328944331],
      [-73.6178740199084, 45.4828487105026],
      [-73.6188871149392, 45.4826094451865],
      [-73.6212759199926, 45.4802684345737],
      [-73.6225662166532, 45.4809098124242],
      [-73.6236079242847, 45.479859834089],
      [-73.6247644644914, 45.4792722536745],
      [-73.6274376104247, 45.4787022686984],
      [-73.6296262215988, 45.478422071886],
      [-73.6309839979771, 45.4790336481084],
      [-73.6303804074798, 45.4796761714723],
      [-73.6511475576679, 45.4890232837666],
      [-73.6486185977978, 45.4918874029923],
      [-73.6505027283703, 45.4926843456098],
      [-73.6558244313911, 45.4867907549359],
      [-73.6554964724779, 45.4865593791057],
      [-73.6559518311015, 45.4851214751334],
      [-73.6560231568666, 45.4789400952457],
      [-73.6611067166692, 45.4811529055447],
      [-73.6618618884249, 45.4803203895973],
      [-73.6695855765435, 45.483802365291],
      [-73.6746342471328, 45.4819683440264],
      [-73.6763145414839, 45.4831298265322],
      [-73.6776271543493, 45.4823345919293],
      [-73.677264286648, 45.4836591822082],
      [-73.6751680903633, 45.4912833590877],
      [-73.6678730495106, 45.4869534898132],
      [-73.6660964808822, 45.4866186123515],
      [-73.665349200462, 45.4870183659149],
      [-73.6562276688947, 45.49432722353],
      [-73.6637510731136, 45.4992450684359],
      [-73.6617471598017, 45.4992191258018],
      [-73.6623623016746, 45.5022066512214],
      [-73.6605369493135, 45.5024306141327],
      [-73.6600841825714, 45.50331916613],
      [-73.659999506549, 45.5047080114556],
      [-73.6566453499119, 45.5037588241059],
      [-73.6516126661051, 45.504311872331],
      [-73.6458072174417, 45.5016289991394]]]},
   'properties': {'district': '33-Snowdon'},
   'id': '33'},
  {'type': 'Feature',
   'geometry': {'type': 'Polygon',
    'coordinates': [[[-73.6143642141962, 45.4835868912093],
      [-73.6123997707291, 45.4826898974257],
      [-73.6143764334436, 45.4805885224868],
      [-73.6054346259738, 45.4765925587108],
      [-73.605024536716, 45.4770080719998],
      [-73.5985471562789, 45.4740708829885],
      [-73.5951347718664, 45.4764466331536],
      [-73.5966486659517, 45.4732210790839],
      [-73.5995923966142, 45.4714885118876],
      [-73.6015380888098, 45.4698449656495],
      [-73.6025897276388, 45.4690525247808],
      [-73.6031619796725, 45.4691032161751],
      [-73.6056266168094, 45.4676031109374],
      [-73.6058459619009, 45.4672881102352],
      [-73.6116004847967, 45.4647691120724],
      [-73.6121904900053, 45.4648542087469],
      [-73.6157015928197, 45.4632907897894],
      [-73.6167538282606, 45.4637150194085],
      [-73.6260868871444, 45.4678594502274],
      [-73.626514031426, 45.4682540051731],
      [-73.6317531402478, 45.4705324186308],
      [-73.6328791824832, 45.4692477650227],
      [-73.6375349663401, 45.4712784001916],
      [-73.636638362928, 45.4717833758261],
      [-73.6429334550997, 45.4745543212637],
      [-73.6397624769414, 45.4766952953752],
      [-73.6393702983563, 45.4768105158646],
      [-73.6354876412699, 45.4768957315274],
      [-73.6324931664858, 45.477871983287],
      [-73.6296262215988, 45.478422071886],
      [-73.6274376104247, 45.4787022686984],
      [-73.6247644644914, 45.4792722536745],

In [45]:
## Outline symbol maps.
import plotly.express as px
df = px.data.gapminder()
fig = px.scatter_geo(df, locations="iso_alpha", color="continent", hover_name="country", size="pop",
               animation_frame="year", projection="natural earth")
fig.show()

In [46]:
px.data.gapminder()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [47]:
## Choropleth maps.
import plotly.express as px
df = px.data.gapminder()
fig = px.choropleth(df, locations="iso_alpha", color="lifeExp", hover_name="country", animation_frame="year", range_color=[20,80])
fig.show()

#### 18.3.5.8 Polar Coordinates

In [48]:
## Polar plots.
import plotly.express as px

df = px.data.wind()
fig = px.scatter_polar(df, r="frequency", theta="direction", color="strength", symbol="strength",
            color_discrete_sequence=px.colors.sequential.Plasma_r)
fig.show()

In [49]:
px.data.wind()

    direction strength  frequency
0           N      0-1        0.5
1         NNE      0-1        0.6
2          NE      0-1        0.5
3         ENE      0-1        0.4
4           E      0-1        0.4
..        ...      ...        ...
123       WSW       6+        0.1
124         W       6+        0.9
125       WNW       6+        2.2
126        NW       6+        1.5
127       NNW       6+        0.2

[128 rows x 3 columns]

In [50]:
## Radar charts.
import plotly.express as px

df = px.data.wind()
fig = px.line_polar(df, r="frequency", theta="direction", color="strength", line_close=True,
            color_discrete_sequence=px.colors.sequential.Plasma_r)
fig.show()

In [51]:
## Polar bar charts.
import plotly.express as px

df = px.data.wind()
fig = px.bar_polar(df, r="frequency", theta="direction", color="strength", template="plotly_dark",
            color_discrete_sequence= px.colors.sequential.Plasma_r)
fig.show()

#### 18.3.4.8 Ternary Coordinates
Ternary chart [info](https://plotly.com/python/ternary-plots/)

In [52]:
## Ternary charts.

import plotly.express as px
df = px.data.election()
fig = px.scatter_ternary(df, a="Joly", b="Coderre", c="Bergeron", color="winner", size="total", hover_name="district",
                   size_max=15, color_discrete_map = {"Joly": "blue", "Bergeron": "green", "Coderre":"red"} )
fig.show()